language: ruby
rvm:
 - 2.3.0
    code_climate:
        repo_token: c79f66d08128ec373e911e150208ec90ca038ab2c9dd91734396e4aab076b9f0
# uncomment and edit the following line if your project needs to run something other than Using the default profile...
# script: bundle exec rspec spec
